# -*- coding: utf-8 -*-
"""project part 2 _ part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wh96pftgo6Jwho2lK9PUbDjMmNsozto8

# 🚀 Project Phase 2: Physical Design and Data Staging

Data staging is the process of preparing and organizing data for migration or integration into a data warehouse, data mart, or other analytical environments. In this case, we will be preparing our data for a data mart as intended for this project.


It also involves transforming and cleansing raw data from various sources into a format suitable for analysis and reporting.


This report will contain:

1. Source code (well documented code)

2. Submit a PDF file with the following details.

A. one-page schematic with your high-level data staging plan.  

B. Any other details you want to add.

C. A list of data quality issues you encountered and how you handled them (i.e., how did you detect and handle missing or noisy data (if any). How did you integrate the data from different sources etc.?

D. Fill out the attached excel sheet (Team Planning) and include it in the PDF

# ✏️ Project Preliminaries

Project Phase 2
Physical Design and Data Staging

Due Date: March 27, 2024, 11:59pm

Team #52

Student #1 : Céleste Duguay #300122287

Student #2 : Michel Akotondji #300189827

Student #3: Aïssatou K. Diome #300139476



---


Liens importants:


Github repository:https://github.com/lixu4n/DataMart-Design-And-Implementation

Project Team Planning XLS: https://uottawa-my.sharepoint.com/personal/cdugu093_uottawa_ca/Documents/Phase%202-Team%20Planning_W23_.xlsx?d=w470a72341981471e9f7f412236398574&csf=1&web=1&e=ngb0r1

# 🛒 Data Staging Steps ETL - Extraction

Data can be extracted in various formats, such as CSV, XML, or JSON.

For our project we will be extracting from 3 CSV formats.


1. CSV 1 : Consumer Behavior and Shopping Habits Dataset
https://www.kaggle.com/datasets/zeesolver/consumer-behavior-and-shopping-habits-dataset

2. CSV 2 : E-commerce Customer Data For Behavior Analysis
https://www.kaggle.com/datasets/shriyashjagtap/e-commerce-customer-for-behavior-analysis

3. CSV 3: E-commerce Customer Behvior Dataset
https://www.kaggle.com/datasets/uom190346a/e-commerce-customer-behavior-dataset
"""

# Import Libraries

import pandas as pd
import itertools
import numpy as np
import random
import math

from sklearn.preprocessing import MinMaxScaler

# Might be easier to use RAW Github Urls than load from google drive as it is better for access and collaboration.

# shopping_behavior_updated.csv (CSV1)
url1 = "https://raw.githubusercontent.com/lixu4n/DataMart-Design-And-Implementation/main/shopping_behavior_updated.csv?token=GHSAT0AAAAAACMDFQODBU4JMXCDJLLZ5UGUZP3TXPA"
dataset1 = pd.read_csv(url1)

# ecommerce_customer_data_custom_ratios.csv (CSV2)
url2 = "https://raw.githubusercontent.com/lixu4n/DataMart-Design-And-Implementation/main/ecommerce_customer_data_custom_ratios.csv?token=GHSAT0AAAAAACMDFQODV5DYK2SE5GYNWJMSZP3TUVQ"
dataset2 = pd.read_csv(url2)

# E-commerce Customer Behavior - Sheet1.csv (CSV3)
url3 = "https://raw.githubusercontent.com/lixu4n/DataMart-Design-And-Implementation/main/E-commerce%20Customer%20Behavior%20-%20Sheet1.csv?token=GHSAT0AAAAAACMDFQOCVVCNTCFPCXQM2D6CZP3TVGQ"
dataset3 = pd.read_csv(url3)

# Display first rows  -

dataset1.head(10)

# Display first rows  - ecommerce_customer_data_custom_ratios.csv (CSV2)

dataset2.head(10)

# Display first rows  - ecommerce_customer_data_large.csv (CSV3

dataset3.head(10)

# Get all colums display - Amazon Customer Behavior Survey.csv (CSV1)
dataset1.columns

# Get all colums display - Amazon Customer Behavior Survey.csv (CSV1)
dataset2.columns

# Get all colums display - Amazon Customer Behavior Survey.csv (CSV1)
dataset3.columns



# Datasets colums types

print(dataset1.dtypes)
print(dataset2.dtypes)
print(dataset3.dtypes)

"""# 🛒 Data Staging Steps ETL - Transformation - Data Cleaning

Handling duplicates, dropping unwanted columns and changing data types
"""

# b. Dropping Rows or Columns: Remove rows or columns
# with a high proportion of missing values if they cannot be reasonably imputed.

# Here we will perfrom a dropping a few colums in order to prepare to merge the datasets together.

dataset1 = dataset1.drop(columns=['Size', 'Color', 'Subscription Status', 'Shipping Type', 'Promo Code Used', 'Previous Purchases', 'Payment Method'])

print(dataset1.dtypes)

# Convert seasons to respective int value from 1-4

dataset1['Season'] = dataset1['Season'].replace('Winter', 1)
dataset1['Season'] = dataset1['Season'].replace('Spring', 2)
dataset1['Season'] = dataset1['Season'].replace('Summer', 3)
dataset1['Season'] = dataset1['Season'].replace('Fall', 4)

# Convert column season to int

dataset1['Season'] = dataset1['Season'].astype(int)
print(dataset1.dtypes)

dataset1.head(10)

dataset2 = dataset2.drop(columns=['Payment Method', 'Customer Age', 'Returns', 'Customer Name'])

print(dataset2.dtypes)
dataset2.head(10)

# Convert 'Purchase Date' to datetime
dataset2['Purchase Date'] = pd.to_datetime(dataset2['Purchase Date'], infer_datetime_format=True)


# Convert seasons to respective int value from 1-4 using the datetime format
dataset2['Season'] = np.where(dataset2['Purchase Date'].dt.month.isin([12, 1, 2]), 1,
                              np.where(dataset2['Purchase Date'].dt.month.isin([3, 4, 5]), 2,
                              np.where(dataset2['Purchase Date'].dt.month.isin([6, 7, 8]), 3,
                              np.where(dataset2['Purchase Date'].dt.month.isin([9, 10, 11]), 4, np.nan))))

# Convert column 'Season' to int
dataset2['Season'] = dataset2['Season'].astype(int)

# Convert 'Purchase Date' to just the date part after season calculation
dataset2['Purchase Date'] = dataset2['Purchase Date'].dt.date


print(dataset2.dtypes)
dataset2.head(10)

# dataset3
dataset3 = dataset3.drop(columns=['Membership Type', 'Days Since Last Purchase'])
print(dataset3.dtypes)
dataset3.head(10)

"""**Handling missing values**


  1. Handling missing values
  2. Scaling and Normlization!
  
Scaling down numeric variables to a range between 0 and 1, also known as normalization, has several benefits:

Uniformity: It brings all the numeric features within the same scale, ensuring that no single feature dominates due to its larger magnitude.

Interpretability: Scaling to a range between 0 and 1 preserves the relative differences in the data while making it easier to interpret. For instance, if Age ranges from 20 to 60 and Purchase Amount ranges from 100 to 1000, after scaling, you know that an increase of 0.1 in a feature represents an increase of 10% within the original range.
"""

#handle missing values
dataset1.fillna(method='ffill', inplace=True)  # forward fill imputation
dataset2.fillna(method='ffill', inplace=True)  # foward fill imputation
dataset1.fillna(method='ffill', inplace=True)  # forward fill imputation

"""Normalization

"""

# Normalize numeric val
scaler = MinMaxScaler()
dataset1[[ 'Review Rating']] = scaler.fit_transform(dataset1[[ 'Review Rating']])

dataset2[[ 'Quantity', 'Total Purchase Amount']] = scaler.fit_transform(dataset2[[ 'Quantity', 'Total Purchase Amount']])
dataset3[['Total Spend', 'Items Purchased', 'Average Rating']] = scaler.fit_transform(dataset3[['Total Spend', 'Items Purchased', 'Average Rating']])

"""# **Dataset Integration**"""

# Intégration des données sur la colonne Customer ID
merged_data = pd.merge(dataset1, dataset2, on="Customer ID", how="inner")
merged_data = pd.merge(merged_data, dataset3, on="Customer ID", how="inner")

print(merged_data.head(5))

"""# **DISCRETIZATION**"""

integrated_df = merged_data

# Définition des intervalles de prix
price_bins = [0, 30, 60, 90, float('inf')]
price_labels = ['Prix abordable', 'Prix moyen', 'Prix modéré', 'Prix élevé']

# Discrétisation des données sur les prix
integrated_df['Price_Category'] = pd.cut(integrated_df['Purchase Amount (USD)'], bins=price_bins, labels=price_labels, right=False)

print("Integrated Dataset Price Category Value Counts:")
print(integrated_df['Price_Category'].value_counts())

# Définition des intervalles d'âge
age_bins = [0, 18, 30, 50, float('inf')]
age_labels = ['Enfant', 'Jeune', 'Adulte', 'Vieux']

# Discrétisation des données sur l'âge
integrated_df['Age_Category'] = pd.cut(integrated_df['Age'], bins=age_bins, labels=age_labels, right=False)

print("Integrated Dataset Age Category Value Counts:")
print(integrated_df['Age_Category'].value_counts())

"""# Loading"""

# Générer des clés substituées pour customer id
customer_id_mapping = {customer_id: idx for idx, customer_id in enumerate(integrated_df['Customer ID'].unique(), start=1)}

# nouvelle colonne avec les clés substituées
integrated_df['Customer ID Substituted'] = integrated_df['Customer ID'].map(customer_id_mapping)

# DataFrame avec les clés substituées
integrated_df.to_csv("integrated_dataset_with_substituted_keys.csv", index=False)

# Chargement de l'ensemble de données final avec les clés substituées
final_dataset_with_substituted_keys = pd.read_csv("integrated_dataset_with_substituted_keys.csv")

dataset_final = pd.read_csv("integrated_dataset_with_substituted_keys.csv")
print(dataset_final.head(3))

"""# Our data mart using a Database Management System (DBMS)"""

import sqlite3

# connexion à la base de données (elle sera créée)
conn = sqlite3.connect('spotify.db')

# curseur pour exécuter des commandes SQL
cursor = conn.cursor()

# Chargement du dataset final avec les clés substituées à partir du fichier CSV
integrated_df_with_keys = pd.read_csv("integrated_dataset_with_substituted_keys.csv")

# Insertion des données dans la table du datamart
integrated_df_with_keys.to_sql('Datamart', conn, if_exists='replace', index=False)

# Validation des changements
conn.commit()

print("Le datamart a été créé avec succès à partir du dataset final.")

"""# 📊 Project Phase 3 - OLAP + BI Dashboard

# Part 1 -  Standard OLAP Operations

a. Explore and collect

1. Exploring purchases by category and year:
"""

# Connexion à la base de données
conn = sqlite3.connect('spotify.db')
cursor = conn.cursor()

# Exécution de la requête SQL
query = """
SELECT Category, strftime('%Y', "Date_d'achat") AS Year, COUNT(DISTINCT "Customer ID") AS Total_Clients
FROM Datamart
GROUP BY Category, Year;
"""
cursor.execute(query)


results1 = cursor.fetchall()
for row in results1:
    print(row)

"""2. Cumul des achats par mois"""

cursor = conn.cursor()

query = """
SELECT strftime('%m', "Date_d'achat") AS Month,
       SUM("Purchase Amount (USD)") AS Total_Achats
FROM Datamart
GROUP BY Month
ORDER BY Month;
"""
cursor.execute(query)


results2 = cursor.fetchall()
for row in results2:
    print(row)

# le résultat indique un total de 104 373

"""b.Tranche, où une seule cote est sélectionnée
3. Nombre d'achats pour l'article 'Lunettes de soleil' :
"""

cursor = conn.cursor()

query = """
SELECT COUNT(*) AS Total_Achats_Lunettes_de_soleil
FROM Datamart
WHERE "Item Purchased" = 'Sunglasses';
"""
cursor.execute(query)


results3 = cursor.fetchall()
for row in results3:
    print(row)

"""C.Dés, où l’on crée un sous‐cube
4. Sous-cube des achats par mois et catégorie :
"""

cursor = conn.cursor()

query = """
SELECT strftime('%m', "Date_d'achat") AS Month, Category, COUNT(*) AS Total_Achats
FROM Datamart
GROUP BY Month, Category;

"""
cursor.execute(query)


results4 = cursor.fetchall()
for row in results4:
    print(row)

"""d. Combining OLAP operations.
1. Comparaison des achats entre deux périodes :
"""

import sqlite3

# Connexion à la base de données
conn = sqlite3.connect('spotify.db')
cursor = conn.cursor()

# Exécution de la requête PRAGMA
cursor.execute("PRAGMA table_info(Datamart)")

# Récupération des résultats
columns_info = cursor.fetchall()

# Affichage des noms de colonnes
column_names = [info[1] for info in columns_info]
print(column_names)

cursor = conn.cursor()

query = """
SELECT
    CASE
        WHEN strftime('%m', "Purchase Date") IN ('01','02','03') THEN 1
        WHEN strftime('%m', "Purchase Date") IN ('04','05','06') THEN 2
        WHEN strftime('%m', "Purchase Date") IN ('07','08','09') THEN 3
        ELSE 4
    END AS Season,
    strftime('%Y', "Purchase Date") AS Year,
    SUM("Purchase Amount (USD)") AS Total_Sales
FROM
    Datamart
WHERE
    strftime('%Y', "Purchase Date") IN ('2022', '2023')
GROUP BY
    Season, Year
ORDER BY
    Year, Season;
"""
cursor.execute(query)


results = cursor.fetchall()
results

"""2. Analyse des ventes par région et catégorie"""

cursor = conn.cursor()

query = """
SELECT Location, Category, SUM("Purchase Amount (USD)") AS Total_Sales
FROM Datamart
GROUP BY Location, Category;
"""
cursor.execute(query)


results = cursor.fetchall()
results

"""## 📊 Part 2 - Explorative Operations - 3 queries

a) Iceberg Querie
"""

# Iceberg Query
# In the first query, we will find the top 5 customers with the highest total spend over all purchases...
# we take our full csv file and execute it.

# we select our Customer ID and then calculate all the purchased with the associated id
# we will display by descending order
# we also only display the top 5!
iceberg_query = """
SELECT "Customer ID", SUM("Total Purchase Amount") AS total_spend
FROM Datamart
GROUP BY "Customer ID"
ORDER BY total_spend DESC
LIMIT 5;
"""

# My query -- This is using the Iceberg
cursor.execute(iceberg_query)

# get res
iceberg_results = cursor.fetchall()

# Print the results
print("Top 5 Customers with the Highest Total Spend of all purchases:")
for row in iceberg_results:
    print(row)

# close connection

conn.close()

"""b) Windowing Querie"""

# query : comparaison of each average purchase amount for each customer with the average puchase across all
#using thr windowing query
sql_query = """
SELECT "Customer ID",
       AVG("Total Purchase Amount") AS avg_purchase_amount,
       AVG("Total Purchase Amount") OVER () AS overall_avg_purchase_amount
FROM Datamart
GROUP BY "Customer ID";
"""

# Execution
cursor.execute(sql_query)

results = cursor.fetchall()

# Print
for row in results:
    print(row)

conn.close()

"""c. Using the window clause"""

# this takes the total spend and compare to location.. we will be using the window clause!
sql_query = """
SELECT "Customer ID",
       "Location",
       SUM("Total Purchase Amount") AS total_spend,
       AVG(SUM("Total Purchase Amount")) OVER (PARTITION BY "Location") AS avg_spend_per_location
FROM Datamart
GROUP BY "Customer ID", "Location";
"""

# Execution  query
cursor.execute(sql_query)

results = cursor.fetchall()

# Print
for row in results:
    print(row)

# cursor connection.
cursor.close()
conn.close()

"""In the phase 3 deliverable we also implemented a power bi dashboard to display our data.

# ⛏️ Phase 4 - Data Mining

# PART A

# 1. Résumé des données

**i) Nuages de points :**

Nous créons ici des nuages de points pour explorer les relations entre différentes variables, telles que l'âge et le montant des achats et ensuite la note de révision et le montant des achats. Cela nous permettra de visualiser s'il existe des tendances ou des corrélations entre ces variables.
"""

import matplotlib.pyplot as plt
import seaborn as sns

#les données
data = pd.read_csv("integrated_dataset_with_substituted_keys.csv")

# Visualisation de la relation entre l'âge et le montant des achats avec une ligne de régression
plt.figure(figsize=(8, 6))
sns.regplot(data=data, x='Age', y='Purchase Amount (USD)', scatter_kws={'alpha':0.5})
plt.title('Relation entre l\'âge et le montant des achats')
plt.xlabel('Âge')
plt.ylabel('Montant des achats (USD)')
plt.show()

# Nuage de points pour explorer la relation entre la note de révision et le montant des achats
plt.figure(figsize=(8, 6))
sns.regplot(data=data, x='Review Rating', y='Purchase Amount (USD)',scatter_kws={'alpha':0.5})
plt.title('Relation entre la note de révision et le montant des achats')
plt.xlabel('Note de révision')
plt.ylabel('Montant des achats (USD)')
plt.show()

"""**ii) Boîtes à moustaches :**

Nous utilisons des boîtes à moustaches pour visualiser la distribution des données numériques telles que l'âge, le montant des achats et la note de révision. Elles fourniront des informations sur la médiane, les quartiles et les valeurs aberrantes dans ces variables.
"""

# Boîte à moustaches pour visualiser la distribution de l'âge
plt.figure(figsize=(8, 6))
sns.boxplot(data=data, y='Age')
plt.title('Distribution de l\'âge')
plt.ylabel('Âge')
plt.show()

# Boîte à moustaches pour visualiser la distribution du montant des achats
plt.figure(figsize=(8, 6))
sns.boxplot(data=data, y='Purchase Amount (USD)')
plt.title('Distribution du montant des achats')
plt.ylabel('Montant des achats (USD)')
plt.show()

# Calcule des statistiques pour l'âge
age_median = np.median(data['Age'])
age_q1 = np.percentile(data['Age'], 25)
age_q3 = np.percentile(data['Age'], 75)
age_iqr = age_q3 - age_q1
age_lower_bound = age_q1 - 1.5 * age_iqr
age_upper_bound = age_q3 + 1.5 * age_iqr

print("Statistiques pour l'âge:")
print("Médiane:", age_median)
print("Premier quartile (Q1):", age_q1)
print("Troisième quartile (Q3):", age_q3)
print("Écart interquartile (IQR):", age_iqr)
print("Limite inférieure (1.5 * IQR):", age_lower_bound)
print("Limite supérieure (1.5 * IQR):", age_upper_bound)

# Calcule des statistiques pour le montant des achats
purchase_amount_median = np.median(data['Purchase Amount (USD)'])
purchase_amount_q1 = np.percentile(data['Purchase Amount (USD)'], 25)
purchase_amount_q3 = np.percentile(data['Purchase Amount (USD)'], 75)
purchase_amount_iqr = purchase_amount_q3 - purchase_amount_q1

print("\nStatistiques pour le montant des achats:")
print("Médiane:", purchase_amount_median)
print("Premier quartile (Q1):", purchase_amount_q1)
print("Troisième quartile (Q3):", purchase_amount_q3)
print("Écart interquartile (IQR):", purchase_amount_iqr)

"""a) Pour l'âge :

La médiane est de 32 ans, ce qui signifie que la moitié des individus ont un âge inférieur ou égal à 32 ans et l'autre moitié ont un âge supérieur ou égal à 32 ans.
Le premier quartile (Q1) est de 30 ans, ce qui signifie que 25% des individus ont un âge inférieur ou égal à 30 ans.
Le troisième quartile (Q3) est de 36 ans, ce qui signifie que 75% des individus ont un âge inférieur ou égal à 36 ans.
L'écart interquartile (IQR) est de 6 ans.
Les limites inférieure et supérieure pour détecter les valeurs aberrantes sont respectivement de 21 ans et 45 ans. Toute valeur d'âge en dehors de ces limites peut être considérée comme une valeur aberrante.


b) Pour le montant des achats :

La médiane est de 61.0 USD, ce qui signifie que la moitié des montants d'achats sont inférieurs ou égaux à 61.0 USD et l'autre moitié sont supérieurs ou égaux à 61.0 USD.
Le premier quartile (Q1) est de 39.0 USD, ce qui signifie que 25% des montants d'achats sont inférieurs ou égaux à 39.0 USD.
Le troisième quartile (Q3) est de 81.0 USD, ce qui signifie que 75% des montants d'achats sont inférieurs ou égaux à 81.0 USD.
L'écart interquartile (IQR) est de 42.0 USD.

**iii) Histogrammes :**

Nous utilisons les histogrammes pour explorer la distribution des données numériques telles que l'âge, le montant des achats. Cela nous permettra de voir la répartition des valeurs et de détecter des schémas potentiels.
"""

# histogramme pour explorer la distribution de l'âge
plt.figure(figsize=(8, 6))
plt.hist(data['Age'], bins=30, color='skyblue', edgecolor='black')
plt.title('Distribution de l\'âge')
plt.xlabel('Âge')
plt.ylabel('Fréquence')
plt.grid(True)
plt.show()

# histogramme pour explorer la distribution du montant des achats
plt.figure(figsize=(8, 6))
plt.hist(data['Purchase Amount (USD)'], bins=30, color='lightgreen', edgecolor='black')
plt.title('Distribution du montant des achats')
plt.xlabel('Montant des achats (USD)')
plt.ylabel('Fréquence')
plt.grid(True)
plt.show()

"""# 2. Prétraitement des données

**i) Traitement des valeurs manquantes :**

Nous utiliserons des techniques d'imputation pour remplacer les valeurs manquantes par des valeurs estimées. Par exemple, nous allons remplacer les valeurs manquantes numériques par la moyenne ou la médiane des données existantes, et les valeurs catégorielles par la modalité la plus fréquente.
"""

# Imputation des valeurs manquantes numériques avec la moyenne
numerical_columns = data.select_dtypes(include=['int', 'float']).columns
data[numerical_columns] = data[numerical_columns].fillna(data[numerical_columns].mean())

# Imputation des valeurs manquantes catégorielles avec la modalité la plus fréquente
categorical_columns = data.select_dtypes(include=['object']).columns
for col in categorical_columns:
    data[col] = data[col].fillna(data[col].mode()[0])

# Vérification des valeurs manquantes après l'imputation
missing_values = data.isnull().sum()
print("Nombre de valeurs manquantes après imputation :\n", missing_values)

"""Toutes les valeurs manquantes ont été correctement traitées, car le nombre de valeurs manquantes pour chaque colonne est de 0. Cela signifie que nous avons réussi à remplacer les valeurs manquantes par des valeurs estimées, en utilisant la moyenne pour les colonnes numériques et la modalité la plus fréquente pour les colonnes catégorielles. Nos données sont maintenant prêtes pour être utilisées dans des analyses ultérieures ou dans des modèles d'apprentissage automatique.

**ii) Gestion des attributs catégoriels :**

Pour les variables catégorielles, nous utiliserons l'encodage à chaud (One-Hot Encoding) pour les transformer en variables binaires. Cela signifie que chaque catégorie devient une colonne binaire (0 ou 1) dans le jeu de données.
Si les catégories ont un ordre intrinsèque, nous allons également les convertir en données ordinales. Par exemple, si on a des valeurs comme "faible", "moyen" et "élevé", nous allons les encoder comme 0, 1 et 2 respectivement
"""

print("Premières lignes des données :")
print(data.head())

# Encodage à chaud des variables catégorielles
data_encoded = pd.get_dummies(data, columns=['Gender_x', 'Category'])

print("\nDonnées après encodage à chaud :")
print(data_encoded.head())

"""**iii) Normalisation des attributs numériques :**

Nous allons normaliser les attributs numériques pour mettre toutes les variables sur la même échelle. Cela peut être fait en soustrayant la moyenne et en divisant par l'écart-type (z-score normalization), ou en mettant à l'échelle les valeurs dans une plage spécifique (min-max scaling).
"""

# Sélectionner les colonnes numériques à normaliser
colonnes_numeriques = ['Age_x', 'Purchase Amount (USD)', 'Season_x', 'Review Rating', 'Total Spend', 'Items Purchased', 'Average Rating']

# Z-score normalization
data[colonnes_numeriques] = (data[colonnes_numeriques] - data[colonnes_numeriques].mean()) / data[colonnes_numeriques].std()

print("Données après normalisation z-score :")
print(data.head())

"""**iv) Sélection d'entités :**

Pour réduire la complexité du modèle et améliorer les performances, nous allons effectuer une sélection d'entités en supprimant les attributs potentiellement redondants ou peu informatifs. Pour cela, nous allons utiliser des techniques comme l'analyse de corrélation, les méthodes basées sur les arbres (comme l'importance des variables dans les forêts aléatoires).

a) Analyse de corrélation :
"""

# Sélectionner uniquement les colonnes numériques
data_numerique = data.select_dtypes(include=['int', 'float'])

# la matrice de corrélation pour les colonnes numériques
correlation_matrix = data_numerique.corr()

print("Matrice de corrélation :")
print(correlation_matrix)

""" b) Importance des variables dans les forêts aléatoires :"""

from sklearn.ensemble import RandomForestClassifier

# Séparer les variables explicatives et la variable cible
X = data_numerique.drop(columns=['Customer ID'])
y = data_numerique['Customer ID']

# modèle de forêt aléatoire
model = RandomForestClassifier()

# Adaptation du modèle aux données
model.fit(X, y)

#importance des variables
feature_importances = model.feature_importances_

# DataFrame pour visualiser l'importance des variables
feature_importances_df = pd.DataFrame({'Variable': X.columns, 'Importance': feature_importances})

# Trier les variables par importance
feature_importances_df = feature_importances_df.sort_values(by='Importance', ascending=False)


print("Importance des variables :")
print(feature_importances_df)
plt.figure(figsize=(10, 6))
plt.barh(feature_importances_df['Variable'], feature_importances_df['Importance'])
plt.xlabel('Importance')
plt.ylabel('Variable')
plt.title('Importance des variables')
plt.show()

"""# PART B


Classification (Supervised Learning):


My task chosen here is determining if a customer will churn.
"""

# My imports from scikit-learn

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
import time

"""This preprocessing steps to ensure all categorical data is in the right format! All data to build a churn prediction model based on supervides learning."""

import pandas as pd

# Assuming 'data' is your DataFrame containing the dataset

# We drop data not needed for our analysis... why do customer churn? should not be based from purchase date item purchased etc.
data_numeric = data.drop(columns=['Customer ID', 'Item Purchased', 'Location', 'Purchase Date', 'City'])

# Discount could be a leading factor of customers NOT churning. lets process this data for our classifier.
if 'Discount Applied_x' in data_numeric.columns:
    data_numeric['Discount Applied_x'] = data_numeric['Discount Applied_x'].map({'Yes': 1, 'No': 0})

# Same for frequency, analysis how much it is bought in relations from customes behavior.
frequency_mapping = {'Daily': 1, 'Weekly': 2, 'Fortnightly': 3, 'Monthly': 4, 'Quarterly': 5, 'Bi-Weekly': 6}
data_numeric['Frequency of Purchases'] = data_numeric['Frequency of Purchases'].map(frequency_mapping)

"""1. Spliting the data into features such as X and Y

This step is crucial for our supervised learning model. We aim to used the input variables X and target features Y and train our model to know the relationships between the variables.

We wil be using the Churn input in this but it can but any datatypes: numerical, categorical and text etc.
"""

# perfoming encoding steps for our model and ensuring all data is dropped.
data_encoded = pd.get_dummies(data_numeric)
data_encoded = data_encoded.dropna()


# We split our data Churn into features (X) and target variable (y)

X = data_encoded.drop(columns=['Churn'])
y = data_encoded['Churn']

# We prepared our training model by splitting our training and testing sets. We opt to allocate 80% train and 20% test.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#test size can be changed here.

"""2. Result comparaison

In order fror us or clients to understand our model, we will plan accordingly by using dictionaries to store our results.

This will serve us during our analysis in step 3 as well of this part b.
"""

# we will use dictionaries to store our results
accuracy_dict = {}
precision_dict = {}
recall_dict = {}
time_dict = {}

"""3. Building our algorithms


We will use Decision Tree, Gradient Boosting and Random forest algorithms to construct models against our data.

This step is training the so call model....
"""

# Training steps

#Decision Tree Classifier
start_time = time.time()
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)
end_time = time.time()
time_dict['Decision Tree'] = end_time - start_time

#Gradient Boosting classifier
start_time = time.time()
gb_classifier = GradientBoostingClassifier(random_state=42)
gb_classifier.fit(X_train, y_train)
end_time = time.time()
time_dict['Gradient Boosting'] = end_time - start_time

#Random forest classifier
#ensuring we get time for each .
start_time = time.time()
rf_classifier = RandomForestClassifier(random_state=42)
rf_classifier.fit(X_train, y_train)
end_time = time.time()
time_dict['Random Forest'] = end_time - start_time

"""Let's now test our models built. Return the values to perform an analysis."""

#Testing

# decision Tree Classifier
dt_predictions = dt_classifier.predict(X_test)
accuracy_dict['Decision Tree'] = accuracy_score(y_test, dt_predictions)
precision_dict['Decision Tree'] = precision_score(y_test, dt_predictions)
recall_dict['Decision Tree'] = recall_score(y_test, dt_predictions)

# Gradient Boosting Classifier
gb_predictions = gb_classifier.predict(X_test)
accuracy_dict['Gradient Boosting'] = accuracy_score(y_test, gb_predictions)
precision_dict['Gradient Boosting'] = precision_score(y_test, gb_predictions)
recall_dict['Gradient Boosting'] = recall_score(y_test, gb_predictions)

# Random Forest Classifier
rf_predictions = rf_classifier.predict(X_test)
accuracy_dict['Random Forest'] = accuracy_score(y_test, rf_predictions)
precision_dict['Random Forest'] = precision_score(y_test, rf_predictions)
recall_dict['Random Forest'] = recall_score(y_test, rf_predictions)

#Loop through our results, making our results accessible:

#1 - accuracy
print("Accuracy:")
for classifier, accuracy in accuracy_dict.items():
    print(f"{classifier}: {accuracy}")

#2 - Precision
print("\nPrecision:")
for classifier, precision in precision_dict.items():
    print(f"{classifier}: {precision}")

#3 - Recall

print("\nRecall:")
for classifier, recall in recall_dict.items():
    print(f"{classifier}: {recall}")

#4 - Time datatype.
print("\nTime to construct models:")
for classifier, time_taken in time_dict.items():
    print(f"{classifier}: {time_taken} seconds")

"""4. 300-400 word summary of our Classification Supervised Learning

Based on our results we explores many results from each algorithms asked in this task. For our first results, Accuruacy, We can see for most of the algorithms it returns a high rate of predicting churn. This suggests that all three models can be valuable in predicting customer churn based on the provided features. For our next results, precision Precision which mesures the accuracy of positive predictions made by the model. Both the Decision Tree and Random Forest models achieved perfect precision scores of 1.0, meaning they rarely misclassify non-churners as churners. Gradient Boosting performed slightly lower but still is at a percentage of 95.2%. This tells us that the models are reliable in identifying actual churn cases without many false positives.

Now, for our recall, also known as sensitivity, measures the ability of the model to correctly identify all positive instances that we stated in this analysis and model, including true positives and false negatives. The Decision Tree model achieved the highest recall score (92.16%), followed by Random Forest (90.20%), and then Gradient Boosting (78.43%) which is a great difference. This indicates that the Decision Tree model is more effective at capturing all actual churn instances.

 Lastly, we timed all our performances of the models to give us better insights in the runtime of each. This can help us differentiatr which is the best to used in real-life scenarios.The first model is the Decision Tree model which took 0.046 second to construct, while Gradient Boosting and Random Forest models took longer, with construction times of 0.989 and 1.057 seconds, respectively. Despite the longer construction times of Gradient Boosting and Random Forest, they still provided competitive accuracy and precision scores. Run time can be considered but does not determined much about their effectiveness of prediction.

# PART C

## Outliers Detection

Import Librairies
"""

from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler

"""## Preprocess and Feature Selection

Before applying the One-Class SVM, we need to select the numerical features for outlier detection and standardize them to have a mean of 0 and a standard deviation of 1. This normalization is crucial for algorithms like SVM that are sensitive to the scale of the data.

"""

df = pd.read_csv("integrated_dataset_with_substituted_keys.csv")

# Select numerical features for outlier detection
features = df.select_dtypes(include=[np.number])

# Standardize the features
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

"""## Outlier Detection with One-Class SVM

With the data preprocessed, we apply the One-Class SVM to detect outliers. The "nu" parameter is set to control the fraction of outliers the algorithm will tolerate, and "gamma" defines the kernel coefficient for the RBF kernel.

"""

one_class_svm = OneClassSVM(kernel='rbf', nu=0.01, gamma='auto')
outlier_predictions = one_class_svm.fit_predict(features_scaled)

# Add a column to your dataframe to indicate outliers
df['is_outlier'] = outlier_predictions

"""## Display Outliers

Finally, we filter and display the rows identified as outliers by the One-Class SVM. These are the data points that differ significantly from the rest of the dataset according to the algorithm.

"""

# Filter the DataFrame to only include outliers
outliers_only = df[df['is_outlier'] == -1]

# Display dataset with only Outliers
outliers_only